### PR TITLE
locale fixes to rely on the system better

### PR DESCRIPTION
**Pull request by scopatz**
This should address the issues in #447. I would really appreciate it if @ZyX-I or someone else could test this out. Thanks!

### CODE REVIEW

**Comment by ZyX-I** [comment]
This fixes `env | grep LC` and `locale` output: now first shows only `READNULLCMD` as expected and second shows `ru_RU.UTF-8` everywhere except `LC_ALL`. But this is not fixing UnicodeDecodeError for `echo $(printf '\\x99')`.

**Comment by scopatz** [comment]
OK, I think I see what the deconding issue is.  Basically, a lot of Python builtin functionality such as `str.decode()` assumes UTF8. I thought that this assumed the encoding for the system. I am going to go through and add the capability to set the encoding and error handling in the environment. This will be in another PR.

**Comment by ZyX-I** [comment]
@scopatz Note that my locale encoding *is* UTF-8. I do not need setting *other* encodings, I need it accept *non-UTF-8 input*.

One way to do this is using `surrogateescape` `errors` handling method to make it accept all kinds of input:

    b'\xFF'.decode('utf-8', 'surrogateescape').encode('utf-8', 'surrogateescape') == b'\xFF'

**Comment by scopatz** [comment]
@ZyX-I, see #454. This is basically what I did.

**Pull request merged**
