### PR TITLE
hotfix for #1108

### PR DESCRIPTION
**Pull request by scopatz**
@mburo or @gforsyth, can you take a look, please? Thanks in advance!

### CODE REVIEW

**Comment by mburo** [comment]
Alright, so this is a hotfix. How do I apply it - I am not that familiar with git ...

**Comment by scopatz** [comment]
you can do something like:

```console
git checkout -b ns
git pull https://github.com/scopatz/xonsh.git ns
```

**Comment by mburo** [comment]
seems to work

**Comment by scopatz** [comment]
Great thanks!

**Pull request merged**
