### PR TITLE
added setproctitle to conda recipe

### PR DESCRIPTION
**Pull request by scopatz**
Probably for @melund, though anyone is welcome to take a look!

### CODE REVIEW

**Comment by scopatz** [comment]
Also, see discussion on #656

**Comment by melund** [comment]
This is a no-brainer. However, I can't build on windows at the moment since conda build doesn't seem to pick up 'GIT_DESCRIBE_TAG' and 'GIT_DESCRIBE_NUMBER', that is used for versioning the conda packages. It seems to work fine on the Linux worker on Anaconda.org. I will just go ahead and merge it anyway...

**Comment by melund** [comment]
Arggg... What is now this. Any clues @asmeurer ? 

The setproctitle packages were added to the xonsh channel by @scopatz using the `anaconda copy` command. I just added them to the 'dev' channel as well. Did I break something on anaconda.org

```
C:\Users\mel\Documents\xonsh\recipe>conda install -c xonsh/channel/dev xonsh
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: ................................
Package plan for installation in environment C:\Users\mel\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setproctitle-1.1.9         |           py35_0          10 KB
    xonsh-0.2.5                |          py35_29         343 KB
    ------------------------------------------------------------
                                           Total:         353 KB

The following NEW packages will be INSTALLED:

    setproctitle: 1.1.9-py35_0
    xonsh:        0.2.5-py35_29

Proceed ([y]/n)? y

Fetching packages ...
Error: HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://conda.anaconda.org/t/me-3a21d4c4-81c7-4665-93ab-c098742451d2/xonsh/label/dev/win-64/setproctitle-1.1.9-py35_0.tar.bz2: https://conda.anaconda.org/t/me-3a21d4c4-81c7-4665-93ab-c098742451d2/xonsh/channel/dev/win-64/setproctitle-1.1.9-py35_0.tar.bz2


C:\Users\mel\Documents\xonsh\recipe>
```

**Comment by melund** [comment]
Maybe `anaconda copy` still doesn't work as expected. I have asked a question on the conda mailing list: https://groups.google.com/a/continuum.io/forum/#!topic/conda/KULTdZA5Rsw

**Comment by asmeurer** [comment]
Retry maybe? Usually 500 errors from anaconda.org are intermittent. 

Also, you may have just posted a private token in the url in the error message.

**Comment by melund** [comment]
You are right. I just started working again... Damn. I was the only one failing...

Thanks for the warning on the private token. I have remove it and created a new one.

**Comment by melund** [comment]
Or maybe not. Maybe it just picked up a cached version from when I downloaded from conda-forge. I need to test this a little bit more

**Comment by melund** [comment]
After cleaning up all packages in conda I get the error again...
```
Fetching packages ...
Error: HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://conda.anaconda.org/t/me-XXXXX/xonsh/win-64/setproctitle-1.1.9-py35_0.tar.bz2: https://conda.anaconda.org/t/me-XXXXX/xonsh/win-64/setproctitle-1.1.9-py35_0.tar.bz2
```
Do you ( @scopatz @asmeurer ) also see this. What happens if you click any of the files here https://anaconda.org/xonsh/setproctitle/files . It could reveal if it is just related to my user on anaconda.org.

**Comment by scopatz** [comment]
When I look at the files on anaconda.org, I see everything that is supposed to be there.

screenshot 2016-02-05 at 16 30 53 - display 2

I am also, I believe, a member of the conda-forge org. that the package originally came from, though.

**Comment by scopatz** [comment]
(Actually I am not a member of conda-forge on anaconda.org, so nevermind about that)

**Comment by melund** [comment]
Yes. It is not it.  @asmeurer is right.  Anaconda.org is flaky.. Now I could suddenly download once again. 

Next error... I get a permission error when installing setproctitle. 
```
C:\Users\mel\Documents\xonsh\recipe>conda install -c xonsh setproctitle
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: ......................
Package plan for installation in environment C:\Users\mel\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setproctitle-1.1.9         |           py35_0          10 KB

The following NEW packages will be INSTALLED:

    setproctitle: 1.1.9-py35_0

Proceed ([y]/n)? y

Fetching packages ...
setproctitle-1 100% |###############################| Time: 0:00:00 370.33 kB/s
Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda\cli\main.py", line 173, in main
    args_func(args, p)
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda\cli\main.py", line 180, in args_func
    args.func(args, p)
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda\plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda\instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda\install.py", line 485, in extract
    t.extractall(path=path)
  File "C:\Users\mel\Anaconda3\lib\tarfile.py", line 2000, in extractall
    numeric_owner=numeric_owner)
  File "C:\Users\mel\Anaconda3\lib\tarfile.py", line 2042, in extract
    numeric_owner=numeric_owner)
  File "C:\Users\mel\Anaconda3\lib\tarfile.py", line 2112, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\mel\Anaconda3\lib\tarfile.py", line 2152, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\mel\\Anaconda3\\pkgs\\setproctitle-1.1.9-py35_0\\Lib\\site-packages\\setproctitle.cp35-win_amd64.pyd'

C:\Users\mel\Documents\xonsh\recipe>
```

**Comment by asmeurer** [comment]
That's a weird error. Usually that means the file is currently running and Windows has the lock on it, but I don't think that should be happening in the untar phase. Try deleting C:\Users\mel\Anaconda3\pkgs\setproctitle-1.1.9-py35_0.

**Comment by melund** [comment]
Ha ha... A restart did the trick.. Always fun to be stuck with windows :-(

**Comment by melund** [comment]
Thanks, for the suggestion @asmeurer, maybe it had solved it as well.

**Comment by scopatz** [comment]
Uggh very weird error @melund!

**Comment by melund** [comment]
Yes. But now I can confirm that it works. Also with the development channel. @scopatz  Btw. can I get you to activate the webhook to github again. It doesn't build when master is updated. 

You can find it here: https://anaconda.org/xonsh/xonsh/settings/ci

I am a little unsure if you need to alter anything on you github account....

**Comment by scopatz** [comment]
Sure, but is there any way that I could give you access?  Just so that I am not the single point of failure? I think you already have access to the https://anaconda.org/xonsh/xonsh/settings/ci settings.  Do you also need admin access to this repo?

**Comment by melund** [comment]
Well. I am not sure it is really necessary, for this little thing. I think all that is needed is that you just click the EDIT button on https://anaconda.org/xonsh/xonsh/settings/ci and then click 'Update CI'. When I do it I just get the following error:
```
We Could not add a web hook to the repository: (unauthorized: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"})<br> This may mean you do not have admin access to add the webhook in github
```

**Comment by scopatz** [comment]
Ok! I have done so.  Let me know if I need to do anything else.

**Comment by melund** [comment]
It still doesn't seem that the webhook is active.

image

Maybe there is something wrong with Anaconda.org. When I enabled it for one of my own repositories I was forwarded to github where I could acknowlege the hook. I will try to investigate if you can give me rights muck around with xonsh github repo.

**Comment by scopatz** [comment]
Uggh I think I have to do this because  I can't give you webhook permissions: https://help.github.com/articles/permission-levels-for-a-user-account-repository/

**Comment by scopatz** [comment]
Ok, I just tried deleting the webhook from GH manually and then updating at anaconda.org.

**Comment by melund** [comment]
> Uggh I think I have to do this because I can't give you webhook permissions: https://help.github.com/articles/permission-levels-for-a-user-account-repository/

I feared it was so. I still can't see that the webhook should be active. Maybe there is some issues with anaconda.org. Try to toggle the webhook checkbox before you click the 'Update CI' button. I think that did the trick for me.

**Comment by scopatz** [comment]
Just tried that, I am not sure that it did anything.  Should I try removing CI completely and re-implementing it?

**Comment by melund** [comment]
I think that would be the best option. I think there are lot of bugs in the build system on Anaconda.org. It is still a product under development.

**Comment by scopatz** [comment]
Ok, purged and re-implemented.

**Comment by melund** [comment]
Weird that it still does not show the webhook as active. Maybe we should ask on the conda mailing list. One of my other repos looks like this: 

On Anaconda.org: 
image



On github: 
image

**Comment by scopatz** [comment]
Yeah, that is exactly what I see too. I think that we should ask of the mailing list.

**Pull request merged**
