### PR TITLE
The Return of the Dots

### PR DESCRIPTION
**Pull request by gforsyth**
This makes use of the recent additions to `prompt_toolkit` in jonathanslenders/python-prompt-toolkit@7f15fd7c and restores the dots(!) to the margin when you have a multiline block.  

Probably can't / shouldn't merge this until there's another PTK release but in case any of you (like me) were hankering for some dots...

### CODE REVIEW

**Comment by adqm** [comment]
:+1: for dots!

One thing this is currently missing is the ability to specify a custom multiline prompt.  The readline shell uses the [`multiline_prompt`](https://github.com/scopatz/xonsh/blob/master/xonsh/environ.py#L920-L936) function in `environ.py` to figure out what characters to use; can that be easily integrated here?

**Comment by gforsyth** [comment]
Shouldn't be a problem.  Let me take a look at it.

**Comment by gforsyth** [comment]
Hmm -- this breaks the autocompletion menu, something to do with changes to the default layout in `create_prompt_application`.  Will investigate.

**Comment by scopatz** [comment]
Is this ready for another look @gforsyth?

**Comment by gforsyth** [comment]
Hey @scopatz -- it's ready for review.  I still don't think we can merge it until there's a `prompt_toolkit` -- or we can work on a check, since those with newer `prompt_toolkit` will have problems wtih the autocompleter like #643

**Comment by scopatz** [comment]
Ahh right.  Hopefully, that will be coming soon :)

**Comment by scopatz** [comment]
Looks like this now has merge conflicts @gforsyth :(

**Comment by scopatz** [comment]
@gforsyth with ptk v0.58 now released, did you want to update this PR?

**Comment by scopatz** [comment]
Or wait until the color stuff has been merged in again?

**Comment by gforsyth** [comment]
Hey @scopatz, if this passes the tests I think it's good to go.  I also added in a `kwargs.pop` following your lead in #696

**Comment by gforsyth** [comment]
well... nevermind that, then... let me see if I can track that down.

**Comment by gforsyth** [comment]
Huh? Any thoughts @scopatz ?

```
File "C:\projects\xonsh\xonsh\ptk\shell.py", line 11, in <module>
    from pygments.style import Style
ImportError: No module named 'pygments'
```

**Comment by scopatz** [comment]
Figured it out: [this commit](https://github.com/jonathanslenders/python-prompt-toolkit/commit/198e7a18ada0bfabb1c26b5a0093ca5c80b14a68#diff-2eeaed663bd0d25b7e608891384b7298L15) made ptk not depend on pygments at install time anymore for some reason. This means that CI was not picking it up as part of the dependency tree. This attempts to fix the change: 46496c243d55132b771f28f23bea82b33129ecfe

**Comment by scopatz** [comment]
You should be able to cherry pick that commit or merge the c branch into master.  It looks like it is mostly there anyway due to the rprompt branch merger

**Comment by gforsyth** [comment]
Hey @scopatz, this is ready for another look now.

**Comment by scopatz** [comment]
Thanks a ton @gforsyth!

**Pull request merged**
