### PR TITLE
Remove the Python version restriction from the conda recipe

### PR DESCRIPTION
**Pull request by asmeurer**
conda build adds this to the package automatically.

### CODE REVIEW

**Comment by melund** [comment]
Have you tested that this works when using conda convert from Linux to windows...

**Comment by asmeurer** [comment]
I did not.

**Comment by scopatz** [comment]
Thanks @asmeurer!

**Comment by melund** [comment]
@asmeurer . I see what you mean. Conda build added the "3.4*" specificaiton automatically. That means that conda-convert should work correctly.

**Pull request merged**
