### PR TITLE
updating the webm with some slight pauses

### PR DESCRIPTION
**Pull request by SavinaRoja**
Added some small transition pauses in the xonsh-demo.webm

To view the modified file, see https://raw.githubusercontent.com/SavinaRoja/xonsh/master/docs/_static/xonsh-demo.webm

### CODE REVIEW

**Comment by scopatz** [comment]
I am happy too merge this @SavinaRoja - but I don't want too many versions of the file in the repo.  Are there any other changes you are expecting to make?  If not I'll go ahead and put it in. Thanks again!

**Comment by SavinaRoja** [comment]
@scopatz This replaces the current version. I felt that the pauses were necessary to make it easier for people to pause and review; I doubt we will see any need to change this file further, until such time as it becomes factually inaccurate.

**Comment by scopatz** [comment]
Ok! Thanks.

**Comment by scopatz** [comment]
New docs are now live.

**Pull request merged**
