### PR TITLE
added xo xontrib metadata

### PR DESCRIPTION
**Pull request by scopatz**
which provides a modicum of speed benefits.

### CODE REVIEW

**Comment by scopatz** [comment]
Also, I snuck in a test to make sure that the JSON metadata file is actually loadable.  This seems like it would be easy to get wrong.

**Comment by melund** [comment]
This looks good. Remember to add xo to conda-forge :)

**Comment by scopatz** [comment]
It is, but sadly it doesn't work with windows because of ncurses :( https://anaconda.org/conda-forge/xo

**Comment by melund** [comment]
Ohh well. I guess I can merge it anyway :)

**Comment by scopatz** [comment]
Yeah... Sorry... I thought that ncurses and urwid worked on windows when I started that project. At least I learned my lesson with xonsh :)

**Pull request merged**
