### PR TITLE
Potential zsh fixes

### PR DESCRIPTION
**Pull request by scopatz**
@moigagoo, would you mind trying this out, please? Thanks!

### CODE REVIEW

**Comment by moigagoo** [comment]
Tried this fix. Still no luck:
```
/usr/local/lib/python3.5/site-packages/xonsh/foreign_shells.py:251: RuntimeWarning: JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)

could not parse /bin/zsh functions:
  s  = '__XONSH_ENV_BEG__\nTMPDIR=/var/folders/gd/wx6527ws00b10j7sf872vrl80000gn/T/\nTERM_PROGRAM_VERSION=361.1\nApple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.tGblU67RhG/Render\nLC_CTYPE=UTF-8\nTERM_PROGRAM=Apple_Terminal\nXPC_SERVICE_NAME=0\nXPC_FLAGS=0x0\nTERM_SESSION_ID=C67D2507-B89F-4D0B-AC1A-F758BAC080E5\nSSH_AUTH_SOCK=/private/tmp/com.apple.launchd.d3u17JJJlN/Listeners\nTERM=xterm-256color\n__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0\nSHELL=/usr/local/bin/xonsh\nHOME=/Users/kmolchanov\nLOGNAME=kmolchanov\nUSER=kmolchanov\nPATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin\n__PYVENV_LAUNCHER__=/usr/local/Cellar/python3/3.5.1/bin/python3.5\nSHLVL=1\nPWD=/Users/kmolchanov\nOLDPWD=/Users/kmolchanov\n_=/usr/bin/env\n__XONSH_ENV_END__\n__XONSH_ALIAS_BEG__\nalias run-help=man\nalias which-command=whence\n__XONSH_ALIAS_END__\n__XONSH_FUNCS_BEG__\n}\n__XONSH_FUNCS_END__\n'
  g1 = '}\n'

Note: you may be seeing this error if you use zsh with prezto. Prezto overwrites GNU coreutils functions (like echo) with its own zsh functions. Please try disabling prezto.
  warn(msg.format(exc, shell, s, g1), RuntimeWarning)
```

**Comment by scopatz** [comment]
This is good actually! I recognize where this error is coming from.

**Comment by scopatz** [comment]
Ok @moigagoo. Try it now, please!

**Comment by moigagoo** [comment]
It works! :+1:

Thanks a ton!

**Comment by scopatz** [comment]
Amazing! Finally!

**Pull request merged**
