### PR TITLE
Deterministic tests

### PR DESCRIPTION
**Pull request by scopatz**
This is an attempt to make the tests deterministic and address #1014.  @melund, if you get a chance would you mind seeing if this works on Windows? Thanks!

### CODE REVIEW

**Comment by melund** [comment]
I get this error. 
```
======================================================================
FAIL: test_tools.test_executables_in
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mel\Documents\xonsh\tests\test_tools.py", line 513, in test_executables_in
    assert_equal(expected, result)
AssertionError: Items in the second set but not the first:
'29'
'14'
'53'
'26'
'50'
'5'
'62'
'2'
'38'
'17'
'41'

----------------------------------------------------------------------
Ran 132617 tests in 34.972s

FAILED (SKIP=8, failures=1)
```

**Comment by melund** [comment]
But hey. Now it is the same error every time :)

**Comment by scopatz** [comment]
Progress!

**Comment by scopatz** [comment]
How about now?

**Comment by melund** [comment]
Same error. Did some research and I am thinking it may have something to do with the limited functionality of `os.chmod()` on windows. 

>Note Although Windows supports chmod(), you can only set the file’s read-only flag with it (via the stat.S_IWRITE and stat.S_IREAD constants or a corresponding integer value). All other bits are ignored.

https://docs.python.org/3/library/os.html#os.chmod

So on windows you just need to change the file extension to '.exe' to make it executable. That should be picked up by `os.access(filename,os.X_OK)` which is used by `execultables_in()`

**Comment by scopatz** [comment]
Ahh, I see.  Thanks!  Hopefully this latest change will work then...

**Comment by melund** [comment]
O

**Comment by melund** [comment]
Still fails. Seems like I was partly wrong. Not about the extension part, but it seems that `os.access(filename, os.X_OK)` is always true. 

```
(Pdb) p list(executables_in(test_path))
['1.exe', '10.exe', '13.exe', '14', '17', '18.exe', '2', '21.exe', '22.exe', '25.exe', '26', '29', '30.exe', '33.exe', '34.exe', '37.exe', '38', '41', '42.exe', '45.exe', '46.exe', '49.exe', '5', '50', '53', '54.exe', '57.exe', '58.exe', '6.exe', '61.exe', '62', '9.exe']
(Pdb)
```

I guess that the `executables_in()` function actually doesn't work on windows. Maybe that is also why the `which.py` module relies on the extension and only check `os.access` when it is not running on windows: https://github.com/scopatz/xonsh/blob/master/xonsh/xoreutils/_which.py#L151

I am off to bed now. I hope you can manage a release if that is still the plan :)

**Comment by melund** [comment]
The `executables_in()` is doubled by the `yield_executables()` in `envrionment.py` 

https://github.com/scopatz/xonsh/blob/d69c09f4708a9efe946ef780205ffb9ca87ee79b/xonsh/environ.py#L768

I guess `yield_executables()` is not optimized with the `scandir()` stuff, but it understands executables on windows. 

I guess they should really be merged and moved to the new `platforms.py` module.

**Comment by melund** [comment]
I have a fix incoming for this.

**Pull request merged**
