### PR TITLE
fixed SUID issues, I think

### PR DESCRIPTION
**Pull request by scopatz**
I would appreciate it if @larsks and @adqm could take a look. Thanks!

### CODE REVIEW

**Comment by larsks** [comment]
This completely fails to address the problem I reported.  The problem is in the `_is_binary` method, which blows up when run on a file that is not readable, such as a binary with 4111 (that is `s--x--x--x`, which means "suid and executable but **not readable**").

That is why my patch would return `True` if there was an `EACCES` error trying to open the file in `_is_binary`.  This is the *only* possible course of action in this situation, because since the file is not readable *you cannot make any determination about its content*.

With this patch in place, attempting to run `sudo` when it has mode 4111 will still result in:

    $ sudo ls
    xonsh: subprocess mode: permission denied: sudo

**Comment by scopatz** [comment]
OK, I see what you are saying.  I believe that I have fixed the logic issue with reading files that don't have read permission.

**Comment by adqm** [comment]
This looks like it has the right logic now (the question of checking this permission rather than using try/except is, I think, inconsequential).  What is the reason for the `ON_POSIX` check?  Is it not possible for this to happen on Windows?

**Comment by scopatz** [comment]
I don't know what is / is not possible on Windows, but I assume that their permissions model is different and doesn't support SUID. The `ON_POSIX` check was just to be safe since the only complaints about executable, non-readable files have been from sudo.

**Comment by larsks** [comment]
With the latest commit things seem to work.  I would rewrite the comments to be less specific to `sudo`, because there may be other binaries with similar configurations (e.g., on my system, `ssh-agent` is installed with no read access).

I confess to not understanding the purpose of the `get_script_subproc_command` method in general, unless it's largely to make things work on Windows environments.  In a Unix environment, I feel as if the whole thing could be replaced by `return [fname] + args` and it would be simpler and more robust.

**Comment by scopatz** [comment]
Updated comment to be less sudo specific. Thanks for testing.  I think that this is ready to be merged.

**Comment by adqm** [comment]
> I confess to not understanding the purpose of the get_script_subproc_command method in general, unless it's largely to make things work on Windows environments. In a Unix environment, I feel as if the whole thing could be replaced by return [fname] + args and it would be simpler and more robust.

It is largely to deal with Windows, yes, since I don't believe Windows pays any attention to shebangs by default.  There is also a question of what to do if a script is marked as executable but has no shebang.  We currently default to using xonsh as the interpreter in that case.

I do agree that this piece of code could probably be simplified, but that can wait for a different PR, I think.  For now, I will merge this in.

**Pull request merged**
