### PR TITLE
ArchLinux instructions

### PR DESCRIPTION
**Pull request by kseistrup**
Instruct for installing xonsh with yaourt or aura added.

### CODE REVIEW

**Comment by scopatz** [comment]
Sorry to bother, but could you please move these below conda? Thanks

**Comment by kseistrup** [comment]
I don't know how to change a pull request, I sent another…

**Comment by michaelaye** [comment]
u just commit again, it auto-updates.

**Comment by michaelaye** [comment]
has to be same branch, then it works auto-magically.

**Comment by kseistrup** [comment]
Thanks! :)

**Pull request closed without merging**
