### PR TITLE
Add optional dependency on the win_unicode_console library

### PR DESCRIPTION
**Pull request by melund**
It enables utf-8 support in windows terminals. ( https://pypi.python.org/pypi/win_unicode_console )

It is only active if win_unicode_console is installed, and it can be disabled by setting `$WIN_UNICODE_CONSOLE` to False. Setting the env-var also enables/disables on the fly.

We better test for a while our self ( @BYK ) to see if there are any unwanted side-effects. 

Install with:
```
conda install -c xonsh win_unicode_console
pip install win_unicode_console
```

### CODE REVIEW

**Comment by melund** [comment]
Hmm. I will look at why it fails tomorrow.

**Comment by melund** [comment]
I like how ['DEFAULT_ENSURERS'](https://github.com/scopatz/xonsh/blob/master/xonsh/environ.py#L58) can be used to implement ´setters´ on environment variables :)

**Comment by scopatz** [comment]
I'm glad :)

**Comment by scopatz** [comment]
Please let us know when you think it is ready!

**Comment by melund** [comment]
Well. It is ready. But I would like to run with it for a while to make sure there are no unexpected side effect. On the other hand it is only active if people have actively installed win_unicode_console ... So maybe it OK to merge.....

**Comment by scopatz** [comment]
Yeah, I think that this is ready to go in.  Could you make a mention in the docs and the CHANGELOG, please?

**Comment by melund** [comment]
Sorry. I forgot about the change log. I also added some stuff to the windows.rst file. I think it is ready now @scopatz

**Comment by scopatz** [comment]
Looks great! Thanks!

**Pull request merged**
