### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by scopatz**
This fleshes out the aliases page.  It also moves the environment variable definitions to their own page and restructures the source to make it more readable.

### CODE REVIEW

**Comment by adqm** [comment]
I am having trouble building the docs (I get a divide-by-zero error somehow (?), both on master and on this branch), so I am temporarily unable to help with this particular PR... :\

**Comment by scopatz** [comment]
Hmmm weird. Can you post another issue with the zero division error?

**Comment by scopatz** [comment]
Thanks!

**Comment by scopatz** [comment]
Merging for v0.2

**Pull request merged**
