### PR TITLE
Modify string regex (allow multiline strings)

### PR DESCRIPTION
**Pull request by wrywerytwreywery**
I believe this fixes the issue from #92, allowing xonsh to handle multline strings.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @wrywerytwreywery!  For some reason multiline strings still don't work in xonshrc, but this is great.

**Comment by wrywerytwreywery** [comment]
Can you paste in what you tried, specifically?  I put the following in my xonshrc as a quick test, and it seems to work:

```
print("""hey
""")

print('''

test

'\'

''')
```

**Comment by scopatz** [comment]
Hah! You are right.  It works.  It was that I didn't have a newline at the end of my xonshrc. I thought that I had fixed that bug.... maybe not.  I'll take a look now.

**Comment by scopatz** [comment]
Ok that bug is now fixed in master (c48b255)

**Pull request merged**
