### PR TITLE
allow user to enable vi_mode in prompt_toolkit

### LINKED ISSUE #491: make vi mode configurable when using prompt-toolkit
The readline module automatically determines which key-bindings to use by reading `~/.inputrc`. Prompt-toolkit does not appear to have anything analogous. Vi mode can be enabled by passing `vi_mode=True` to the `prompt()` function. But a better option for xonsh is to pass `enable_vi_mode=True` to the `KeyBindingManager()` call.

To be determined is how to tell xonsh to use vi or emacs mode. It could parse `~/.inputrc` for compatibility with readline. But it's probably simpler to use a xonsh specific config option and or CLI argument.

### PR DESCRIPTION
**Pull request by gforsyth**
This adds the envvar `VI_MODE`, (default `False`).  If it is set to `True`,
either in a `.xonshrc` or dynamically, then the prompt is switched to
`vi_mode`.

`vi_mode` defaults to an `--insert--` environment, then user can hit ESC
to enter command mode, etc...'

Resolves #491

### CODE REVIEW

**Comment by krader1961** [comment]
lgtm

**Comment by krader1961** [comment]
FWIW, At some point I'd like to see a discussion about whether the primary, and for the most part only, means of configuring Xonsh specific features should be via environment variables that are exported to every subprocess. I'm dismayed by the huge number of mostly Xonsh specific environment vars listed on http://xonsh.org/envvars.html.

**Comment by gforsyth** [comment]
Might as well open an issue for that.

Are you dismayed regarding performance or regarding style/architecture/etc?

**Comment by scopatz** [comment]
Seems like there is a merge conflict. Would you mind updating @gforsyth? Thanks!

**Comment by gforsyth** [comment]
@scopatz -- merge conflict resolved (I conflicted with my own PR -- that's embarrassing).  I also noticed a bug I introduced that was throwing an exception on exiting `xonsh` but that's cleaned up now.

**Comment by scopatz** [comment]
> I conflicted with my own PR -- that's embarrassing

Happens to the best of us :).  Thanks for the PR!

**Pull request merged**
