### PR TITLE
Adds scripts/xonsh.bat to .gitattribues

### PR DESCRIPTION
**Pull request by funkyfuture**
also fixes its order

### CODE REVIEW

**Comment by GuillaumeLeclerc** [comment]
Great Idea :)

**Comment by funkyfuture** [comment]
though it doesn't help ...

**Comment by funkyfuture** [comment]
@melund mentioned in the chat that it could have an lf-ending. then should i just leave to the order so the second statement has an effect?

**Comment by melund** [comment]
It appears that this file was ones added with `crlf` line ending. So that is screwing thing up for you. I don't now why other don't have the issue. 

I think it is safe to change it back to `lf` in git. When it is checked out on windows it will still be changed back to `crlf`. See https://github.com/scopatz/xonsh/pull/906

**Comment by GuillaumeLeclerc** [comment]
I always see this file as "modified" but even when I `git add` it does not get staged

**Comment by melund** [comment]
What is your output of `git config --global core.eol`

**Comment by melund** [comment]
This probably what bites us: 
> When text=auto normalization is enabled in an existing repository, any text files containing CRLFs should be normalized. If they are not they will be normalized the next time someone tries to change them, causing unfortunate misattribution. From a clean working directory:

from https://git-scm.com/docs/gitattributes

**Comment by melund** [comment]
So I think if https://github.com/scopatz/xonsh/pull/906 is merged, you should stop having the issues.

**Comment by melund** [comment]
I may be necessary to clear cache..
```
git rm --cached -r .
git reset --hard
```

**Comment by funkyfuture** [comment]
> What is your output of git config --global core.eol

none.

**Comment by melund** [comment]
I think we should wait with this one and see if #906 fixes it.

**Comment by scopatz** [comment]
@melund it seems like this is also a reasonable change.  Any reason not to merge it?

**Comment by melund** [comment]
Just want to see what effect the other PR had. Let wait a day until we hear how it works for @funkyfuture and @GuillaumeLeclerc

**Comment by scopatz** [comment]
Ok!

**Comment by funkyfuture** [comment]
yes, it helped. thanks! i repushed an updated commit.

**Comment by melund** [comment]
Great. The error was not normalizing all ´crlf`after `* text=auto` was added. I will you merge this now

**Pull request merged**
