### PR TITLE
Zsh support

### LINKED ISSUE #484: Build out zsh function sourcing & aliasing
Equivalent to what is there now for Bash.

### LINKED ISSUE #662: Static Config: Can't use zsh as foreign shell
```
$ cat ~.config/xonsh/config.json
"foreign_shells": [
        {"shell": "/bin/zsh"}
    ]

$ xonsh
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.5', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 166, in main
    args = premain(argv)
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 153, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/lib/python3.5/site-packages/xonsh/shell.py", line 61, in __init__
    self._init_environ(ctx, config, rc)
  File "/usr/local/lib/python3.5/site-packages/xonsh/shell.py", line 99, in _init_environ
    self.execer = Execer(config=config)
  File "/usr/local/lib/python3.5/site-packages/xonsh/execer.py", line 40, in __init__
    load_builtins(execer=self, config=config)
  File "/usr/local/lib/python3.5/site-packages/xonsh/built_ins.py", line 673, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config))
  File "/usr/local/lib/python3.5/site-packages/xonsh/environ.py", line 1099, in default_env
    issue_warning=False))
  File "/usr/local/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 379, in load_foreign_envs
    shenv, _ = foreign_shell_data(**shell)
  File "/usr/local/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 151, in foreign_shell_data
    funcs = parse_funcs(s, shell=shell, sourcer=sourcer)
  File "/usr/local/lib/python3.5/site-packages/xonsh/foreign_shells.py", line 212, in parse_funcs
    namefiles = json.loads(g1.strip())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### PR DESCRIPTION
**Pull request by scopatz**
This aims to close #484 and fix #662.  I also discovered a couple of issues related to sourcing from files with spaces in their names.

@moigagoo, would you mind testing this out? My simple tests seemed to indicate that everything works, but it would be nice to test it some more.

### CODE REVIEW

**Comment by moigagoo** [comment]
@scopatz I'm afraid, it doesn't work. xonsh crashes with the same traceback as in #662.

To test, I've installed xonsh from the latest "zsh" branch and replaces "bash" with "zsh" in config.json. I also tried it with login=true and login=false, no difference. Here's my current config.json:
```
{
    "env": {
        "HOMEBREW_GITHUB_API_TOKEN": "secret_stuff_here",
        "LC_ALL": "en_US.UTF-8",
        "LANG": "en_US.UTF-8",
        "SHELL_TYPE": "prompt_toolkit"
    },
    "foreign_shells": [
        {
            "shell": "/bin/bash",
            "login": true
        }
    ]
}
```

**Comment by scopatz** [comment]
Hi @moigagoo, not sure what is going on here.  Could you try just sourcing a zsh script or your zshrc file with the `source-zsh`?

**Comment by moigagoo** [comment]
When I launch `$ source-zsh .zshrc`, the shell hangs. It doesn't respond to Ctrl+C.

I forgot to mention that I use prezto with zsh. Maybe, it's causing issues.

**Comment by scopatz** [comment]
What is prezto?

**Comment by scopatz** [comment]
Ok @moigagoo, I just added some more debugging information.  Can you try it again and report back please?  I also suspect what is going wrong, but I want to be sure.  Additionally, I tried your config setup and everything worked fine for me.

**Comment by moigagoo** [comment]
@scopatz [Prezto](https://github.com/sorin-ionescu/prezto) is a configuration framework for zsh. It adds its init.zsh file to .zshrc.

Tried your latest commits. Here's the console output:
```
/usr/local/lib/python3.5/site-packages/xonsh/foreign_shells.py:244: RuntimeWarning: JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)

could not parse /bin/zsh functions:
  s  = '__XONSH_ENV_BEG__\nTMPDIR=/var/folders/gd/wx6527ws00b10j7sf872vrl80000gn/T/\nTERM_PROGRAM_VERSION=361.1\nApple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.tGblU67RhG/Render\nLC_CTYPE=UTF-8\nTERM_PROGRAM=Apple_Terminal\nXPC_SERVICE_NAME=0\nXPC_FLAGS=0x0\nTERM_SESSION_ID=B1F9FDDB-B718-40A0-87FD-175B57BCD45A\nSSH_AUTH_SOCK=/private/tmp/com.apple.launchd.d3u17JJJlN/Listeners\nTERM=xterm-256color\n__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0\nSHELL=/usr/local/bin/xonsh\nHOME=/Users/kmolchanov\nLOGNAME=kmolchanov\nUSER=kmolchanov\nPATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin\n__PYVENV_LAUNCHER__=/usr/local/Cellar/python3/3.5.1/bin/python3.5\nSHLVL=1\nPWD=/Users/kmolchanov/Projects\nOLDPWD=/Users/kmolchanov\nBROWSER=open\nEDITOR=nano\nVISUAL=nano\nPAGER=less\nLANG=en_US.UTF-8\nLESS=-F -g -i -M -R -S -w -X -z-4\nLESS_TERMCAP_mb=\x1b[01;31m\nLESS_TERMCAP_md=\x1b[01;31m\nLESS_TERMCAP_me=\x1b[0m\nLESS_TERMCAP_se=\x1b[0m\nLESS_TERMCAP_so=\x1b[00;47;30m\nLESS_TERMCAP_ue=\x1b[0m\nLESS_TERMCAP_us=\x1b[01;32m\nLSCOLORS=exfxcxdxbxGxDxabagacad\nLS_COLORS=di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:\nGREP_COLOR=37;45\nGREP_COLORS=mt=37;45\nLC_ALL=en_US.UTF-8\nHOMEBREW_GITHUB_API_TOKEN=78da6ccf122b27d3c031e7512ceb30484121573d\n_=/usr/bin/env\n__XONSH_ENV_END__\n__XONSH_ALIAS_BEG__\n1=\'cd +1\'\n2=\'cd +2\'\n3=\'cd +3\'\n4=\'cd +4\'\n5=\'cd +5\'\n6=\'cd +6\'\n7=\'cd +7\'\n8=\'cd +8\'\n9=\'cd +9\'\n_=sudo\nack=\'nocorrect ack\'\nb=\'${(z)BROWSER}\'\nbower=\'noglob bower\'\ncd=\'nocorrect cd\'\ncp=\'nocorrect cp -i\'\nd=\'dirs -v\'\ndf=\'df -kh\'\ndu=\'du -kh\'\ne=\'${(z)VISUAL:-${(z)EDITOR}}\'\nebuild=\'nocorrect ebuild\'\nfc=\'noglob fc\'\nfind=\'noglob find\'\nftp=\'noglob ftp\'\ngcc=\'nocorrect gcc\'\nget=\'curl --continue-at - --location --progress-bar --remote-name --remote-time\'\ngist=\'nocorrect gist\'\ngrep=\'nocorrect grep --color=auto\'\nheroku=\'nocorrect heroku\'\nhistory=\'noglob history\'\nhistory-stat=\'history 0 | awk \'\'{print $2}\'\' | sort | uniq -c | sort -n -r | head\'\nhttp-serve=\'python -m SimpleHTTPServer\'\nl=\'ls -1A\'\nla=\'ll -A\'\nlc=\'lt -c\'\nlk=\'ll -Sr\'\nll=\'ls -lh\'\nlm=\'la | "$PAGER"\'\nln=\'nocorrect ln -i\'\nlocate=\'noglob locate\'\nlr=\'ll -R\'\nls=\'ls -G\'\nlt=\'ll -tr\'\nlu=\'lt -u\'\nlx=\'ll -XB\'\nman=\'nocorrect man\'\nmkdir=\'nocorrect mkdir -p\'\nmv=\'nocorrect mv -i\'\nmysql=\'nocorrect mysql\'\no=open\np=\'${(z)PAGER}\'\npbc=pbcopy\npbp=pbpaste\npo=popd\npu=pushd\nrake=\'noglob rake\'\nrm=\'nocorrect rm -i\'\nrsync=\'noglob rsync\'\nrun-help=man\nscp=\'noglob scp\'\nsftp=\'noglob sftp\'\nsl=ls\ntopc=\'top -o cpu\'\ntopm=\'top -o vsize\'\ntype=\'type -a\'\nwhich-command=whence\n__XONSH_ALIAS_END__\n__XONSH_FUNCS_BEG__\n__XONSH_FUNCS_END__\n\nThank you. Come again!\n  -- Dr. Apu Nahasapeemapetilon\n'
  g1 = ''

  warn(msg.format(exc, shell, s, g1), RuntimeWarning)
```

**Comment by scopatz** [comment]
OK this is not what I was expecting at all.  First off `__XONSH_FUNCS_BEG__\n__XONSH_FUNCS_END__\n` should have *something* between them, rather than just a newline.  I also have no idea where the `Thank you. Come again!\n  -- Dr. Apu Nahasapeemapetilon` is coming from.  Is that a prezto thing?  It seems like prezto might be selectively capturing stdout or redefining echo.

**Comment by scopatz** [comment]
Ok, I am pretty sure that this is the prezto issue: https://github.com/sorin-ionescu/prezto/blob/master/modules/gnu-utility/init.zsh

Prezto wraps all gnu core utilities (echo included) in zsh functions. I have no idea why anyone would want this. I also have no idea why this would work in some cases but not others.  In your login shell, can you try setting `login` to true for zsh? http://xonsh.org/xonshconfig.html#foreign-shells

**Comment by moigagoo** [comment]
@scopatz The output I sent was produced with login=true.

I suggest you just ignore Prezto and put a warning in the docs. Supporting vanilla zsh is good enough.

**Comment by scopatz** [comment]
Ahh ok. Does this work as it is with vanilla zsh? If so, I am happy to make a mention in the docs and merge it in.

**Comment by moigagoo** [comment]
@scopatz Damn, I just accidentally deleted all zsh and prezto configs with backups :-( My zsh isn't running properly even when launched standalone, so any test I run now would be not representative. Sorry about that. Still, I think it's safe to close the issue and blame the error on Prezto since it's clear it hacks gnu functions.

Well, I guess there's no turning back—I have to stick with xonsh now :-D

**Comment by scopatz** [comment]
> @scopatz Damn, I just accidentally deleted all zsh and prezto configs with backups :-(

Oh no! 

> Well, I guess there's no turning back—I have to stick with xonsh now :-D

Haha OK.  We'll make it the best that we can!

**Comment by scopatz** [comment]
Thanks for testing this out @moigagoo

**Comment by moigagoo** [comment]
@scopatz FYI I restored vanilla zsh on my Mac and tried using it as a foreign shell now. Here's what I got in the console:
```
/usr/local/lib/python3.5/site-packages/xonsh/foreign_shells.py:244: RuntimeWarning: JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)

could not parse /bin/zsh functions:
  s  = '__XONSH_ENV_BEG__\nTMPDIR=/var/folders/gd/wx6527ws00b10j7sf872vrl80000gn/T/\nTERM_PROGRAM_VERSION=361.1\nApple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.tGblU67RhG/Render\nLC_CTYPE=UTF-8\nTERM_PROGRAM=Apple_Terminal\nXPC_SERVICE_NAME=0\nXPC_FLAGS=0x0\nTERM_SESSION_ID=049B3B8F-AE21-46C1-BDB8-392E8B65AF3A\nSSH_AUTH_SOCK=/private/tmp/com.apple.launchd.d3u17JJJlN/Listeners\nTERM=xterm-256color\n__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0\nSHELL=/usr/local/bin/xonsh\nHOME=/Users/kmolchanov\nLOGNAME=kmolchanov\nUSER=kmolchanov\nPATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin\n__PYVENV_LAUNCHER__=/usr/local/Cellar/python3/3.5.1/bin/python3.5\nSHLVL=1\nPWD=/Users/kmolchanov\nOLDPWD=/Users/kmolchanov\n_=/usr/bin/env\n__XONSH_ENV_END__\n__XONSH_ALIAS_BEG__\nrun-help=man\nwhich-command=whence\n__XONSH_ALIAS_END__\n__XONSH_FUNCS_BEG__\n__XONSH_FUNCS_END__\n'
  g1 = ''

  warn(msg.format(exc, shell, s, g1), RuntimeWarning)
```

**Comment by scopatz** [comment]
Very strange, does this happen even if `safe` is set to false?

**Comment by scopatz** [comment]
nevermind, that won't change anything.

**Comment by scopatz** [comment]
@moigagoo, can you take a stab at #670 and we con continue the conversation there.  I think I see what was going wrong.

**Comment by esafak** [comment]
I get `xonsh: subprocess mode: command not found: nocorrect` when running `man` with `zsh`.

**Comment by scopatz** [comment]
Hi @esafak, what exactly are you doing? Can you walk us through, step-by-step, please. Thanks!

**Comment by nsp** [comment]
I'm also getting the `nocorrect` error. Turns out that in prezto `cd` (and many other commands) are aliased to use the nocorrect zsh function, which disables autocorrect. Maybe there's a way to define a similar nocorrect function (or at least one that is a no-op)?

**Comment by esafak** [comment]
@scopatz I also have cd aliased to nocorrect with prezto, but it works now.

**Comment by scopatz** [comment]
@esafak is there a specific thing that we should be adding to xonsh? Sorry I am not a zsh expert...

**Comment by esafak** [comment]
Not for me, since it works.

**Comment by scopatz** [comment]
Ok cool!

**Comment by nsp** [comment]
Well, it didn't work for me until I commented out all of the aliases. It seems to be fine now, but would be nice if xonsh and prezto played well from the start. Is there more info I could provide about my setup?

**Comment by scopatz** [comment]
Hi All, I don't really know what errors you are seeing or what the appropriate solution is. Is it just a matter of rejecting certain aliases that are knonw to be non-functioning? If so, is there a programatic or algorithmic way to identify these aliases?

I am happy to have better interop....

**Pull request merged**
