### PR TITLE
fix for alias expansion

### LINKED ISSUE #779: Environment variables don't expand in aliases
```
aaronmeurer🐚 aliases['testing'] = "echo $PATH"
aaronmeurer🐚 testing
$PATH
```

### PR DESCRIPTION
**Pull request by scopatz**
Also this implements the long-overdue moving of the Aliases class to aliases.py. This is an attempt to fix #779.  @asmeurer does this work for you?

### CODE REVIEW

**Comment by melund** [comment]
It gives me this error when launching xonsh

```
C:\Users\mel\Documents\xonsh>xonsh
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\Scripts\xonsh-script.py", line 9, in <module>
    load_entry_point('xonsh', 'console_scripts', 'xonsh')()
  File "C:\Users\mel\Anaconda3\lib\site-packages\setuptools-20.2.2-py3.5.egg\pkg_resources\__init__.py", line 549, in load_entry_point
  File "C:\Users\mel\Anaconda3\lib\site-packages\setuptools-20.2.2-py3.5.egg\pkg_resources\__init__.py", line 2542, in load_entry_point
  File "C:\Users\mel\Anaconda3\lib\site-packages\setuptools-20.2.2-py3.5.egg\pkg_resources\__init__.py", line 2202, in load
  File "C:\Users\mel\Anaconda3\lib\site-packages\setuptools-20.2.2-py3.5.egg\pkg_resources\__init__.py", line 2208, in resolve
  File "c:\users\mel\documents\xonsh\xonsh\main.py", line 16, in <module>
    from xonsh.shell import Shell
  File "c:\users\mel\documents\xonsh\xonsh\shell.py", line 7, in <module>
    from xonsh.execer import Execer
  File "c:\users\mel\documents\xonsh\xonsh\execer.py", line 11, in <module>
    from xonsh.built_ins import load_builtins, unload_builtins
  File "c:\users\mel\documents\xonsh\xonsh\built_ins.py", line 32, in <module>
    from xonsh.aliases import Aliases
  File "c:\users\mel\documents\xonsh\xonsh\aliases.py", line 373, in <module>
    if not locate_binary('sudo'):
  File "c:\users\mel\documents\xonsh\xonsh\environ.py", line 743, in locate_binary
    directories = builtins.__xonsh_env__.get('PATH')
AttributeError: module 'builtins' has no attribute '__xonsh_env__'
```

**Comment by gforsyth** [comment]
Works well on my end.

**Comment by scopatz** [comment]
This was a windows issue, sorry @melund!  Could you try it now?

**Comment by melund** [comment]
This looks good to me as well. I will merge it in.

**Pull request merged**
