### PR TITLE
prompt-toolkit history now reads from xonsh history rather its own custom pickle method.

### PR DESCRIPTION
**Pull request by scopatz**
This addresses #551.

### CODE REVIEW

**Comment by adqm** [comment]
I am getting a little bit of weird behavior here.  It looks like the history is being shared fine.  I can run commands in readline, quit out, and get them in prompt_toolkit; but I can't access the history via the up/down arrows from a fresh prompt_toolkit shell until after I have run a command or hit control C.  After I have done that once, though, then it is all there.  Do you know what might be the issue there?

**Comment by scopatz** [comment]
Hmm I noticed that too.  Looking into it now.

**Comment by scopatz** [comment]
Interestingly, it only effects the first command.  I think that this is because we set up a new `prompt()` each time.

**Comment by scopatz** [comment]
So I think that the lack of up-down on the first command is actually an issue with prompt-toolkit itself.  There is no way when using the `prompt()` function to get access to the `Buffer` instance that is created.  Even using dirty tricks like `gc.get_refferers()` doesn't really work because [the buffer makes a copy of the history](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/buffer.py#L268).  This effectively prevents asynchronous loading of the history. I have tried to load the history synchronously, but it adds too much to the start up time to be useful even for a few thousand history elements.

I vote that we merge this and I open an issue on prompt-toolkit.  Does that sound reasonable?

**Comment by adqm** [comment]
That works for me, assuming the tests pass.  In the slightly longer term, though, we might want to move away from using the `prompt` function, and instead work at a lower level in prompt_toolkit (though I'm not sure exactly what that entails).

**Comment by scopatz** [comment]
Yeah, I agree.  The prompt function is relatively simply but we'd want to make a class out of it (or use the PrompToolkitShell) so that we have access to there variables that it sets up.  I'll make a xonsh issue for that too.

**Pull request merged**
