### PR TITLE
#763 fixed ';' input on tools.subproc_toks()

### PR DESCRIPTION
**Pull request by lucasicf**
Partially solved. Still throwing error in another part of the code.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @lucasicf! This seems like a good start.  What is the other error that is being thrown?

**Comment by lucasicf** [comment]
After I fixed the `tools.subproc_toks()` problem (returns None on only [';']), now `execer._parse_ctx_free()` tries to call `subproc_toks()` after `xonsh.parsers.v35.parse()` returns `SyntaxError`.

It happens in both 3.4 and 3.5 versions of Python.

```
Traceback (most recent call last):
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/execer.py", line 148, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/parsers/base.py", line 285, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/parsers/base.py", line 2302, in p_error
    column=p.lexpos))
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/parsers/base.py", line 380, in _parse_error
    raise err
SyntaxError: <xonsh-code>:1:0: ('code: ;',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/linojosa/.virtualenvs/xonsh-dev/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.7', 'console_scripts', 'xonsh')()
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/main.py", line 239, in main
    shell.cmdloop()
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 111, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 80, in singleline
    display_completions_in_columns=multicolumn)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/shortcuts.py", line 104, in prompt
    document = cli.run(reset_current_buffer=False)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 370, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 150, in run
    t()
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 373, in feed
    self._input_parser.send(c)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 292, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 325, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 899, in feed_key
    self._active_cli.input_processor.feed_key(key_press)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 172, in feed_key
    self._process_coroutine.send(key_press)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 144, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 187, in _call_handler
    handler.call(event)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/prompt_toolkit/key_binding/registry.py", line 33, in call
    return self.handler(event)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/key_bindings.py", line 132, in multiline_carriage_return
    carriage_return(b, event.cli)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/key_bindings.py", line 55, in carriage_return
    elif not current_line_blank and not can_compile(b.document.text):
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/ptk/key_bindings.py", line 102, in can_compile
    locs=builtins.__xonsh_ctx__)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/execer.py", line 92, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/execer.py", line 67, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/Users/linojosa/.virtualenvs/xonsh-dev/lib/python3.5/site-packages/xonsh/execer.py", line 190, in _parse_ctx_free
    if sbpline.lstrip().startswith('$[$['):
AttributeError: 'NoneType' object has no attribute 'lstrip'
```

**Comment by scopatz** [comment]
Ahh OK, So I think if you take the `if sbline....` block on https://github.com/scopatz/xonsh/blob/master/xonsh/execer.py#L190 and make it into an `elif` block of the `if-else` block below it, this will fix that error.  Do you mind putting in another PR for that?

**Comment by lucasicf** [comment]
Sorry I have been quite busy. Sure I'll try that! Hope to do that on this weekend. Thanks

**Comment by scopatz** [comment]
Ahh No worries @lucasicf! I have put in a PR for this under #891. Maybe you wouldn't mind taking a look though!

**Comment by lucasicf** [comment]
thanks @scopatz!

**Pull request merged**
