### PR TITLE
added command-not-found capability for ubuntu and debian

### PR DESCRIPTION
**Pull request by scopatz**
This adds the feature described in #280

### CODE REVIEW

**Comment by adqm** [comment]
Hi @scopatz; sorry for being so absent (that probably won't improve much the rest of the summer, unfortunately).

I think this is a good idea, but a few things:

* If `command-not-found` doesn't exist, but the other suggester offers suggestions, I get two blank lines after the entry:
```
hartz@lappy-508 ~ $ gemtail
xonsh: subprocess mode: command not found: gemtail
Did you mean one of the following?
    getmail:  Alias
    email:    Alias


hartz@lappy-508 ~ $
```

* After installing `command-not-found`, it seems like the version in Debian Jessie (the current stable release) uses a different CLI than the one on Ubuntu.  After installing that, I get:
```
hartz@lappy-508 ~ $ gemtail
xonsh: subprocess mode: command not found: gemtail
Did you mean one of the following?
    getmail:  Alias
    email:    Alias

Usage: command-not-found [options] <command-name>

command-not-found: error: no such option: --no-failure-msg
hartz@lappy-508 ~ $
```

  If it's helpful, the `command-not-found` version on Debian Jessie is 0.2.26.

* Even if `command-not-found` is installed and uses the right CLI, I am not sure the output will be pretty when concatenating the two outputs (we may want to modify the output of `command-not-found`, and/or of the current suggestions).  I think at the very least, this will report that the command in question was not found multiple times (3?): once from my suggester, once at the start of the `command-not-found` output, and once at the end of the `command-not-found` output).  That's a lot of verbosity for a user to have to navigate to get the appropriate suggestions...

  Oooohh, maybe the `--no-failure-msg` flag is supposed to handle this?

**Comment by scopatz** [comment]
Hi @adqm, thanks for the feedback and testing. I have fixed the issues that you mentioned.  You are correct about the purpose of `--no-failure-msg`, but it was one line to re-implement it manually :). 

> sorry for being so absent (that probably won't improve much the rest of the summer, unfortunately).

No worries!

**Comment by scopatz** [comment]
I think that this is ready for another look.

**Comment by scopatz** [comment]
ping!

**Comment by adqm** [comment]
Sorry for the delay; just merged in.  Looks good!

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
