### PR TITLE
Pipes

### PR DESCRIPTION
**Pull request by jamiees2**
I improved the previous method of returning a tuple from an alias to instead capture output.
This makes for easier alias programming, as there is no worry about somehow holding on to the output to return at the end of the function.

Another thing that this makes possible is to create an alias which perhaps does some sort of long lookup which outputs each step of the way, for example a database lookup.

### CODE REVIEW

**Comment by scopatz** [comment]
Hey @jamiees2 - Could you add the Python Software License to the relevant parts of the code, if you are borrowing from v3.5

**Comment by scopatz** [comment]
Thanks for the PR, btw!

**Comment by jamiees2** [comment]
@scopatz No problem! I added the software license and an explanation for the code.

**Comment by scopatz** [comment]
Thanks @jamiees2! I do like the idea of capturing stdout and stderr naively.  However, I also like the idea of being able to return a tuple of str.  I am going to update it (and the docs) a bit to before merging into master.

**Comment by jamiees2** [comment]
Perhaps the two could be merged at the end? At L296, L299, if the alias returns a tuple, add it to the stdin, stderr output/print it?

**Comment by scopatz** [comment]
Yeah, that is exactly what I was thinking.

**Pull request merged**
