### PR TITLE
Allow python -m xonsh

### PR DESCRIPTION
**Pull request by Carreau**
It seems more pythonistic than `python -m xonsh.main`

--- 

Thoughts?

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @Carreau - It is a great idea.  Probably better to implement this in `__main__.py` or move rename the current `__main__.py`: https://docs.python.org/3/library/__main__.html

**Comment by Carreau** [comment]
I'm confused, this **does** introduce a `__main__.py`, and adding an `if __name__ == '__main__':` in `__init__.py` does not have the same effect.

Or are you asking me to **move** `xonsh/main.py` (without underscore) to `xonsh/__main__.py` ?
That would be a (painful?) change of API, and it's hard/weird to import `__main__` if you need it.

Second possibility: I'm tired and don't understand a thing.

**Comment by melund** [comment]
It should be enough to rename `main.py`to `__main__.py`. I don't think it would be a big issue.

Btw. can we run xonsh directly from source with this command? `python -m xonsh -c "xonsh command"`. I was thinking about this for the pytest framework. Some top level things could be tested this way. But what about the parser tables?

**Comment by scopatz** [comment]
Ahhh I am so sorry @Carreau!  I thought this was in init for some reason.  I was clearly the tired one, as I responded before breakfast. 

In this case, I think this looks good.  Only thing I would suggest is an absolute import. `from xonsh.main ...` for consistency.

**Comment by scopatz** [comment]
I sort of agree with @Carreau, @melund.  I think it is nice to keep the `__x__` files as simple as possible.

**Comment by Carreau** [comment]
> In this case, I think this looks good. Only thing I would suggest is an absolute import. from xonsh.main ... for consistency.

Done.

**Comment by scopatz** [comment]
Sweet! Thanks @Carreau. You are the best and least sleepy!

**Pull request merged**
