### PR TITLE
fix incorrect parsing of command line flags

### LINKED ISSUE #1032: Incorrect parsing of some command line flags
I first noticed this when `nosetests -q` didn't actually run with the `-q` option enabled.  It seems to affect other commands as well:

```
hartz@tabby-3 ~/xonsh $ rmdir --version
/bin/rmdir: failed to remove ‘-’: No such file or directory
```

Maybe this is a side-effect of the changes in #1029?

### PR DESCRIPTION
**Pull request by gforsyth**
One character fix :)

Resolves #1032

### CODE REVIEW

**Comment by adqm** [comment]
Ah, yes; that would make sense!  Merging in now.

**Comment by melund** [comment]
I think this important enough for a 0.3.2 release.  Considering that @scopatz is presenting at pycon on Tuesday, and a lot of people is probably going to try it out.

**Comment by gforsyth** [comment]
@melund -- agreed.  I can push one out later tonight if someone else doesn't get to it

**Comment by scopatz** [comment]
ah yeah I am currently en route to pycon, so any help with the release
would be amazing! my personal opinion is that we should put out
microreleases whenever we want and as frequently as we feel like it. Also
we should all feel free to do so as. I certainly don't want to be a blocker
here. I wrote the release script to hopefully make this as easy and
straightforward as possible.

On Sun, May 29, 2016, 13:48 Gil Forsyth <notifications@github.com> wrote:

> @melund <https://github.com/melund> -- agreed. I can push one out later
> tonight if someone else doesn't get to it
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/scopatz/xonsh/pull/1034#issuecomment-222373216>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AATkKRU7jBZXYGAhSMqFFnVcsVxpXoLEks5qGdFtgaJpZM4IpU4M>
> .
>
-- 

Asst. Prof. Anthony Scopatz
Nuclear Engineering Program
Mechanical Engineering Dept.
University of South Carolina
Affiliated Professor of the University of Haifa
scopatz@cec.sc.edu
Office: (803) 777-7629
Cell: (512) 827-8239
Check my calendar
<https://www.google.com/calendar/embed?src=scopatz%40gmail.com>

**Comment by scopatz** [comment]
so have at!

On Sun, May 29, 2016, 14:44 Anthony Scopatz <scopatz@gmail.com> wrote:

> ah yeah I am currently en route to pycon, so any help with the release
> would be amazing! my personal opinion is that we should put out
> microreleases whenever we want and as frequently as we feel like it. Also
> we should all feel free to do so as. I certainly don't want to be a blocker
> here. I wrote the release script to hopefully make this as easy and
> straightforward as possible.
>
> On Sun, May 29, 2016, 13:48 Gil Forsyth <notifications@github.com> wrote:
>
>> @melund <https://github.com/melund> -- agreed. I can push one out later
>> tonight if someone else doesn't get to it
>>
>> —
>> You are receiving this because you were mentioned.
>>
>>
>> Reply to this email directly, view it on GitHub
>> <https://github.com/scopatz/xonsh/pull/1034#issuecomment-222373216>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AATkKRU7jBZXYGAhSMqFFnVcsVxpXoLEks5qGdFtgaJpZM4IpU4M>
>> .
>>
> --
>
> Asst. Prof. Anthony Scopatz
> Nuclear Engineering Program
> Mechanical Engineering Dept.
> University of South Carolina
> Affiliated Professor of the University of Haifa
> scopatz@cec.sc.edu
> Office: (803) 777-7629
> Cell: (512) 827-8239
> Check my calendar
> <https://www.google.com/calendar/embed?src=scopatz%40gmail.com>
>
-- 

Asst. Prof. Anthony Scopatz
Nuclear Engineering Program
Mechanical Engineering Dept.
University of South Carolina
Affiliated Professor of the University of Haifa
scopatz@cec.sc.edu
Office: (803) 777-7629
Cell: (512) 827-8239
Check my calendar
<https://www.google.com/calendar/embed?src=scopatz%40gmail.com>

**Pull request merged**
