### PR TITLE
support ptk_1.x

### PR DESCRIPTION
**Pull request by Carreau**
cause 1 > 0, so 0.57 < 1.0

### CODE REVIEW

**Comment by gforsyth** [comment]
Thanks, @Carreau.  I like this better than the equivalent part in #820 so I'm going to merge it in and then rebase my bit.

**Comment by Carreau** [comment]
Oh, sorry, I missed #820, I would have PR'd your PR.

**Comment by gforsyth** [comment]
No worries.

**Comment by gforsyth** [comment]
Thanks, @Carreau !

**Pull request merged**
