### PR TITLE
Lexer Refactor

### PR DESCRIPTION
**Pull request by adqm**
This is my first attempt at refactoring the lexer to simplify a bunch of the code and (hopefully) make it easier for new people to dive into.  This patch consolidates the py34 and py35 tokenizers together into a single file and moves almost all of the logic for combining operators from `lexer.py` (with the weird generator semantics) to `tokenize.py` (with more straightforward regular expression matching).

I was hoping for a speedup in the process, but that didn't really happen (though it seems to run at about the same speed as the old lexer).

I have it passing all tests locally, and I ran it through a number of interactive tests, but it could definitely use a detailed look, I think.

### CODE REVIEW

**Comment by adqm** [comment]
And I guess the next step might be just to have the `tokenize.py` module yield the PLY tokens directly, rather than using `lexer.py` as a go-between...

**Comment by scopatz** [comment]
Hi @adqm - this seems awesome!  I like the huge negative diff and the fact that the logic is much simpler :).

However, I am getting a fatal error on startup:

```console
scopatz@artemis ~ $ xonsh
Traceback (most recent call last):
  File "/home/scopatz/.local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.3.0', 'console_scripts', 'xonsh')()
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/setuptools-20.7.0-py3.5.egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/setuptools-20.7.0-py3.5.egg/pkg_resources/__init__.py", line 2569, in load_entry_point
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/setuptools-20.7.0-py3.5.egg/pkg_resources/__init__.py", line 2229, in load
  File "/home/scopatz/miniconda3/lib/python3.5/site-packages/setuptools-20.7.0-py3.5.egg/pkg_resources/__init__.py", line 2235, in resolve
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/main.py", line 17, in <module>
    from xonsh.shell import Shell
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/shell.py", line 9, in <module>
    from xonsh.execer import Execer
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/execer.py", line 10, in <module>
    from xonsh.parser import Parser
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parser.py", line 8, in <module>
    from xonsh.parsers.v35 import Parser
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parsers/v35.py", line 4, in <module>
    from xonsh.parsers.base import BaseParser
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/parsers/base.py", line 11, in <module>
    from xonsh.lexer import Lexer, LexToken
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/lexer.py", line 51, in <module>
    token_map[tokenize.IOREDIRECT] = 'IOREDIRECT'
AttributeError: module 'xonsh.tokenize' has no attribute 'IOREDIRECT'
```

**Comment by adqm** [comment]
Yes, I don't know why that happens, but it does.  Bu a _totally_ fresh install should do the trick.  In fact, I had to destroy my _whole_ install (including the `build` directory, `__pycache__`, and the install in `/usr/local/lib/...`) before reinstalling.  Some weird caching with having the same version number, I think?

Can you try that and let me know if you still have issues?  It is running fine here...

**Comment by scopatz** [comment]
Yeah that fixed it.  That is deeply weird.  Oh well.  I think that this is good to go.  I am going to go ahead and merge, but would you mind letting folks know about the needed purge on gitter, please?

**Comment by adqm** [comment]
Sure thing.  I've not actually _used_ gitter yet, but I guess there's a first time for everything.

**Comment by scopatz** [comment]
haha. truth

**Pull request merged**
