### PR TITLE
Parser Refactor

### PR DESCRIPTION
**Pull request by scopatz**
This is an attempt to refactor the parser to be more maintainable. As such this contains two major conceptual changes:

1. Move Python version specific parsing to subclasses.
2. Simplify logic in parsing methods by removing `len(p)` checks.  This entails more, smaller methods.

Hopefully not more than just myself and @adqm will feel comfortable hacking seriously on this part of the code base.

### CODE REVIEW

**Comment by adqm** [comment]
This is really nice!  The only issue I see is that there are quite a lot of PEP8 issues (mostly trailing whitespace, but a couple missing spaces after commas or things like that).

**Comment by scopatz** [comment]
> This is really nice!

Thanks!

> The only issue I see is that there are quite a lot of PEP8 issues (mostly trailing whitespace, but a couple missing spaces after commas or things like that).

I think I got all of these issues. I may have cheated by updating my text editor ;)

**Comment by scopatz** [comment]
I think this is ready for another look.

**Comment by adqm** [comment]
I still see a few PEP8 errors.  The "long lines" ones are probably hard to avoid in the parser, so I'm not too worried about those.  I'm totally happy to merge in if we're not being sticklers for PEP8.  Just let me know.

If it helps, here are the remaining issues reported by the `pep8` tool that aren't related to long lines:
```
hartz@lappy-513 ~/xonsh $ pep8 xonsh/parsers/base.py | grep -v "too long"
xonsh/parsers/base.py:215:43: E231 missing whitespace after ','
xonsh/parsers/base.py:228:78: E231 missing whitespace after ','
xonsh/parsers/base.py:369:13: E265 block comment should start with '# '
xonsh/parsers/base.py:843:32: E127 continuation line over-indented for visual indent
xonsh/parsers/base.py:1579:76: E502 the backslash is redundant between brackets
xonsh/parsers/base.py:1762:5: E303 too many blank lines (2)
xonsh/parsers/base.py:1766:12: E111 indentation is not a multiple of four
xonsh/parsers/base.py:1768:12: E111 indentation is not a multiple of four
xonsh/parsers/base.py:1934:22: E128 continuation line under-indented for visual indent
xonsh/parsers/base.py:2035:53: E231 missing whitespace after ','
xonsh/parsers/base.py:2054:57: E251 unexpected spaces around keyword / parameter equals
xonsh/parsers/base.py:2054:59: E251 unexpected spaces around keyword / parameter equals
xonsh/parsers/base.py:2163:57: E251 unexpected spaces around keyword / parameter equals
xonsh/parsers/base.py:2163:59: E251 unexpected spaces around keyword / parameter equals
xonsh/parsers/base.py:2207:33: E127 continuation line over-indented for visual indent
```

```
hartz@lappy-513 ~/xonsh $ pep8 xonsh/parsers/v34.py | grep -v "too long"
xonsh/parsers/v34.py:11:1: E302 expected 2 blank lines, found 1
xonsh/parsers/v34.py:33:66: E231 missing whitespace after ','
xonsh/parsers/v34.py:42:18: E128 continuation line under-indented for visual indent
xonsh/parsers/v34.py:43:18: E128 continuation line under-indented for visual indent
xonsh/parsers/v34.py:148:1: W391 blank line at end of file
```

```
hartz@lappy-513 ~/xonsh $ pep8 xonsh/parsers/v35.py | grep -v "too long"
xonsh/parsers/v35.py:11:1: E302 expected 2 blank lines, found 1
xonsh/parsers/v35.py:37:18: E128 continuation line under-indented for visual indent
xonsh/parsers/v35.py:38:18: E128 continuation line under-indented for visual indent
```

**Comment by scopatz** [comment]
Ahh I see, thanks @adqm. I wasn't using `pep8` the program before you mentioned it. I think that this is as good as I can get it without breaking PLY docstrings in some weird way.

**Comment by adqm** [comment]
I think this is a big improvement!  Just merged in.

**Comment by scopatz** [comment]
The parser is dead! Long live the parser!

**Pull request merged**
