### PR TITLE
Version

### PR DESCRIPTION
**Pull request by wrywerytwreywery**
As suggested in issue #132, this changeset introduces the xonsh version number as an environment variable `$XONSH_VERSION`.  I also tried to minimize the number of places where the version is hard-coded in the source (though I am not aware of a way to remove it from `meta.yaml`.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for this, @wrywerytwreywery!  I think it is more common to use `__version__` than `VERSION`, though (see PEP8 https://www.python.org/dev/peps/pep-0008/#version-bookkeeping).  Also, for the `meta.yaml`, you are right.  I think the only half-way decent way to do that is to write it out in setup.py.  

I am happy to merge this in as is, but if you want to change the name, let me know!

**Comment by wrywerytwreywery** [comment]
Woops; wasn't aware of that.  I'll go ahead and change the name quickly.

**Comment by scopatz** [comment]
Thanks!

**Comment by wrywerytwreywery** [comment]
Alright; I went ahead and changed the name.  But it felt to weird to me to use the name `__version__` in the files making use of it, so I imported it as `XONSH_VERSION` in all those places.  Is that reasonable?

**Comment by scopatz** [comment]
Yep totally

**Comment by scopatz** [comment]
Hopefully travis will finish before my plane takes off ;)

**Comment by scopatz** [comment]
Thanks!

**Comment by GodFatherandSon** [comment]
Sent from Yahoo Mail on Android

**Pull request merged**
