### PR TITLE
Don't die on JSON config fail

### LINKED ISSUE #908: Xonsh crash when config.json is incorrect
It is very problematic if xonsh is your default shell, You can't display any terminal, and you'd better not have xonsh as the default shell of your root otherwise you'rer even more screwed.

### PR DESCRIPTION
**Pull request by scopatz**
Should fix #908

### CODE REVIEW

**Comment by scopatz** [comment]
finally this works.

**Comment by melund** [comment]
@GuillaumeLeclerc Did this fix it for you?

**Comment by GuillaumeLeclerc** [comment]
No I get this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/xonsh/environ.py", line 1231, in load_static_config
    conf = json.load(f)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 6 column 112 (char 209)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.7', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 224, in main
    args = premain(argv)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 210, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 81, in __init__
    kwargs.get('cacheall', False))
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 121, in _init_environ
    self.execer = Execer(config=config, login=self.login)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 41, in __init__
    load_builtins(execer=self, config=config, login=login)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 672, in load_builtins
    builtins.__xonsh_env__ = ENV = Env(default_env(config=config, login=login))
  File "/usr/local/lib/python3.4/dist-packages/xonsh/environ.py", line 1304, in default_env
    conf = load_static_config(ctx, config=config)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/environ.py", line 1237, in load_static_config
    print_exception()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/tools.py", line 391, in print_exception
    if 'XONSH_SHOW_TRACEBACK' not in builtins.__xonsh_env__:
AttributeError: 'module' object has no attribute '__xonsh_env__'
```

**Comment by scopatz** [comment]
Ok @melund and @GuillaumeLeclerc, I think this was a robustness issue with `xonsh.tools.print_exception()` that I have now addressed.  Could you try it again, please? Thanks!

**Comment by GuillaumeLeclerc** [comment]
The error is detected now but it still make my xonsh crash, thus I can't login on my tty with a improper config.json

here is the traceback:

```
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
ValueError: Expecting property name enclosed in double quotes: line 7 column 39 (char 248)
Xonsh config file is not valid JSON.
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.7', 'console_scripts', 'xonsh')()
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 223, in main
    args = premain(argv)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/main.py", line 209, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 81, in __init__
    kwargs.get('cacheall', False))
  File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 121, in _init_environ
    self.execer = Execer(config=config, login=self.login)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 41, in __init__
    load_builtins(execer=self, config=config, login=login)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 705, in load_builtins
    builtins.aliases.update(load_foreign_aliases(issue_warning=False))
  File "/usr/local/lib/python3.4/dist-packages/xonsh/foreign_shells.py", line 532, in load_foreign_aliases
    shells = _get_shells(shells=shells, config=config, issue_warning=issue_warning)
  File "/usr/local/lib/python3.4/dist-packages/xonsh/foreign_shells.py", line 472, in _get_shells
    conf = json.load(f)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 7 column 39 (char 248)
```

**Comment by scopatz** [comment]
Ok @GuillaumeLeclerc, sorry about that. Please try in now.  This error seemed to crop up in a few places.

**Comment by GuillaumeLeclerc** [comment]
Works fine, I see the errors but it does not kill xonsh. Perfect :) 

I think you can merge this in

**Pull request merged**
