### PR TITLE
make CONTRIBUTING a hard link

### PR DESCRIPTION
**Pull request by gforsyth**
GitHub is weird about symlinks and I think this better represents the
desired behavior (if you click CONTRIBUTING, you should see the dev
guide).

@melund -- do hard links work on Windows?

### CODE REVIEW

**Comment by melund** [comment]
Yes, they work fine.

**Comment by scopatz** [comment]
Crazy, I had no idea hard links worked on windows :)

**Comment by melund** [comment]
Yes. I think it is symbolic links that are implemented slightly different on Windows.

**Comment by asmeurer** [comment]
Hard links work fine in Windows, but they don't work in git. These are now two separate files.

**Comment by melund** [comment]
Yes. Of course. Git uses hard links internally to link files in the worktree. So hard links can't really go into a git repo.

**Comment by gforsyth** [comment]
My bad.  Right now my inclination is to just leave it.  At least people see the right document when they click CONTRIBUTING (for the moment).  

Or, I suppose, we could make the symlink live in the docs folder instead?

**Comment by scopatz** [comment]
> Or, I suppose, we could make the symlink live in the docs folder instead?

Yeah that is probably the best option.... assuming sphinx will pick it up!

**Pull request merged**
