### PR TITLE
New features

### PR DESCRIPTION
**Pull request by jonathanslenders**
Demonstration of new features.

Don't just merge this. Maybe you want to have a configuration somewhere or not have all the features.

This adds:
- mouse support. (Scrolling through completion menus and clicking for selecting the cursor position.)
- auto suggestion (like the fish shell.)

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @jonathanslenders - I can't think of a reason to not want to have these. Is there any good reason to not merge this?

**Comment by mdraw** [comment]
I just tested these changes. The auto-suggestions work perfectly (Thank you so much for this!), but the new "mouse support" breaks my scrolling: I can still scroll in my terminal with Shift+PgUp/PgDown, but scrolling by mouse wheel is no longer possible.
The same issue appears in ptpython with "mouse support" enabled. (Tested on konsole 15.08 and urxvt 9.21)

**Comment by scopatz** [comment]
Hmmm maybe you could open a PR with just the auto-suggestion part of this PR then?

**Comment by scopatz** [comment]
ping! Any updates?

**Comment by mdraw** [comment]
Yes, as soon as https://github.com/jonathanslenders/xonsh/pull/2 is merged into @jonathanslenders' branch, I think this PR can be safely merged into master. Or do you have any criticism about my newly introduced MOUSE_SUPPORT environment variable, @scopatz?

**Comment by scopatz** [comment]
This looks good to me.  Waiting for the OK signal :).

**Comment by mdraw** [comment]
@jonathanslenders do you plan to make some additional changes to this branch or could it be merged now?

Should we maybe make the autosuggestions optional with an environment variable, too? Personally I love this autosuggestion feature, but maybe some others would find it distracting.

**Comment by scopatz** [comment]
This branch also has conflicts now. If you want to resolve those and and the ability to turn the autosuggestion on and off in another PR, I'd really appreciate it!

**Comment by mdraw** [comment]
I can't easily resolve this conflict (which should be easy, it's just one line as far as I can see) because I don't have write access to any of your branches. Making a new PR on top of this now would just further complicate things. I will wait for this PR to be successfully merged and then open a PR for optional autosuggestions, ok?

**Comment by jonathanslenders** [comment]
The merge conficts have been resolved.
There is one bug however. Pressing the Tab key when nothing has been typed yet should indent. This throws:

```python
  File "/home/jonathan/git/xonsh/xonsh/prompt_toolkit_key_bindings.py", line 34, in _
    event.cli.current_buffer.insert_text(env['INDENT'])
  File "/home/jonathan/git/xonsh/xonsh/environ.py", line 254, in __getitem__
    val = self._d[key]
KeyError: 'INDENT'
Exception ignored in: <bound method PromptToolkitShell.__del__ of <xonsh.prompt_toolk>
Traceback (most recent call last):
  File "/home/jonathan/git/xonsh/xonsh/prompt_toolkit_shell.py", line 56, in __del__
  File "/home/jonathan/git/xonsh/xonsh/prompt_toolkit_shell.py", line 33, in teardowny
AttributeError: module 'builtins' has no attribute '__xonsh_env__'
```

**Comment by scopatz** [comment]
Thanks a ton @jonathanslenders, this is because of the new way that environment variable defaults are handled. Instead of `env['INDENT']`, you shou

**Comment by scopatz** [comment]
Sorry about that, you should instead use `env.get('INDENT')`

**Comment by jonathanslenders** [comment]
Fixed.

**Comment by scopatz** [comment]
Thanks a ton @jonathanslenders!  I did some minor cleanup before merging, but it is in.

**Pull request merged**
