### PR TITLE
Tokenizer Fix

### PR DESCRIPTION
**Pull request by adqm**
The built-in `tokenize` module was getting confused with "comments" between backticks (anything with an octothorpe).  See the end of #268.  The first of many parser fixes over the next few days, I hope.

This changeset should fix that problem, though it may not yet fix the original issue.  The fix is a little more involved than I would have liked (including a modified version of `tokenize.py` that knows that regex globbing is special), but I could see no other way.  In fact, it may make sense to move much more of the logic into `xonsh.tokenize` in time.

Also includes a slight refactor to the rest of the lexer (part of a first failed attempt, but still not a bad change).

This is a big diff, so it may be easier to see the changes by looking at individual commits.  The commits for the refactor are separate from the commits for adding the copies of the built-in `tokenize` module, which are separate from the commits for actually updating the tokenize module, which are separate from the commits for modifying the lexer to use the new tokenizer.

### CODE REVIEW

**Comment by scopatz** [comment]
Hey @adqm, this looks great! I think this could use a couple of updates prior to merging:

1. a CHANGELOG entry
2. maybe add the tokenize modules to the API docs?  
3. A simple lexer, parser, or tokenizer test that at least covers the `#.*` case.  I don't think we need anything super complex here.  Just enough to prevent the original error from creeping back in.

In the longer term, it would be interesting to consider if most parts of the forked tokenizers are the same and we only need to have version-specific changes for a small subset, similar to how the parsers work. However, this is not a pressing issue.

Also, I agree that it would be nice to push more of the errortoken things from the lexer back to the tokenizer, eventually :)

**Comment by adqm** [comment]
I just pushed changes to the CHANGELOG and a couple of simple test cases.  I'm not quite sure how best to document the tokenizer.

> In the longer term, it would be interesting to consider if most parts of the forked tokenizers are the same and we only need to have version-specific changes for a small subset, similar to how the parsers work. However, this is not a pressing issue.

Yes, I can do that.  I do think large portions of them are the same (or similar)  Do you think that change should go in here?  Or in a separate PR?

**Comment by scopatz** [comment]
> I'm not quite sure how best to document the tokenizer.

No worries about that. This is an implementation detail.

> Yes, I can do that. I do think large portions of them are the same (or similar) Do you think that change should go in here? Or in a separate PR?

I think a separate PR is better so that we can get this fix in.

**Comment by adqm** [comment]
Okay, great.  In that case, I think this is ready to go.

**Comment by scopatz** [comment]
Great!

**Comment by scopatz** [comment]
Thanks @adqm!

**Pull request merged**
