### PR TITLE
Syntax

### PR DESCRIPTION
**Pull request by wrywerytwreywery**
This is a first go at implementing my suggestion for a new syntax, as discussed in #86.  With this update, `@(...)` evaluates Python code, and `${...}` does environment lookup regardless of context.  Happy to take suggestions for improvement.

### CODE REVIEW

**Comment by scopatz** [comment]
> ${...} does environment lookup regardless of context.

Awesome thanks!

> @(...) evaluates Python code

I still sort of like the `!(...)` syntax. That doesn't block this PR, because it can always be changed again.

@wrywerytwreywery Do you know why travis failed here?

**Comment by scopatz** [comment]
Oh, you probably need to update the tests.

**Comment by wrywerytwreywery** [comment]
I will go ahead and update the tests.

Is it a compromise to support both `!()` and `@()`?  That would be easy, and neither of them collides with any other features...

**Comment by scopatz** [comment]
> Is it a compromise to support both !() and @()? Or is that just bad design? :)

Haha I think that is just bad design.  As long as I think of `@()` as working like a decorator, in that it takes an expression as input and returns something, I am happy with it.  If it really starts to bother us, we can always change it.

**Comment by scopatz** [comment]
Thanks @wrywerytwreywery! This looks great!

**Pull request merged**
