### PR TITLE
fix and tests for mutliple assignment

### PR DESCRIPTION
**Pull request by scopatz**
Should address #147

### CODE REVIEW

**Comment by wrywerytwreywery** [comment]
Hmmm...even though it passes the tests, the following still fails on my machine (?).  It does seem to be tokenizing properly, but I'm getting a syntax error from the parser.

```
$ x, y = 7,8
........................................ 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/xonsh/shell.py", line 140, in push
    locs=self.ctx)
  File "/usr/local/lib/python3.4/site-packages/xonsh/execer.py", line 85, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/site-packages/xonsh/execer.py", line 63, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/usr/local/lib/python3.4/site-packages/xonsh/execer.py", line 120, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/usr/local/lib/python3.4/site-packages/xonsh/parser.py", line 281, in parse
    debug=debug_level)
  File "/usr/local/lib/python3.4/site-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python3.4/site-packages/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python3.4/site-packages/xonsh/parser.py", line 2152, in p_error
    column=p.lexpos))
  File "/usr/local/lib/python3.4/site-packages/xonsh/parser.py", line 350, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: ,',)
```

The following (a little more complicated) also fails, though the simpler `(x,y) = (7,8)` succeeds.

```
$ (x,y) = (z,a) = (7,8)
........................................ 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/xonsh/shell.py", line 140, in push
    locs=self.ctx)
  File "/usr/local/lib/python3.4/site-packages/xonsh/execer.py", line 85, in compile
    tree = self.parse(input, ctx, mode=mode)
  File "/usr/local/lib/python3.4/site-packages/xonsh/execer.py", line 63, in parse
    tree = self._parse_ctx_free(input, mode=mode)
  File "/usr/local/lib/python3.4/site-packages/xonsh/execer.py", line 120, in _parse_ctx_free
    debug_level=self.debug_level)
  File "/usr/local/lib/python3.4/site-packages/xonsh/parser.py", line 281, in parse
    debug=debug_level)
  File "/usr/local/lib/python3.4/site-packages/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python3.4/site-packages/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python3.4/site-packages/xonsh/parser.py", line 2152, in p_error
    column=p.lexpos))
  File "/usr/local/lib/python3.4/site-packages/xonsh/parser.py", line 350, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:4: ('code: (',)
```

**Comment by scopatz** [comment]
Also, `x = y = 10` fails...

**Comment by scopatz** [comment]
Ok try it now.

**Comment by wrywerytwreywery** [comment]
Seems to work for me; thanks for the fix!

**Pull request merged**
