### PR TITLE
Improve handling of which being absent

### PR DESCRIPTION
**Pull request by Will-W**
Error handling for Issue #880

### CODE REVIEW

**Comment by melund** [comment]
He he... I hadn't see this when I also made something similar. My suggestion was to fall back to using where: https://github.com/scopatz/xonsh/pull/885

**Comment by scopatz** [comment]
They both look good to me :)  Which functionality do you both want? Or can they both be merged?

**Comment by melund** [comment]
Personally, I don't care. I have 'which' on my PATH. It is just to ensure that Windows users who don't have 'which' can still get the functionality of looking up aliases. Doesn't make sense to merge both

**Comment by Will-W** [comment]
So there's a philosophical question here about whether the shell should be trying to paper over platform differences. On Windows, it's reasonable to have 'which' not function, if it isn't present. Magically falling back to where means it isn't clear without code inspection what is being run (and installing cygwin would then change the behaviour).

One approach would be to have a **where** wrapper for the underlying Windows 'where', that does the same alias lookup. Then make the error for the 'which' wrapper be something like 'which not found -  try where'.

**Comment by melund** [comment]
It is also nice if xonsh code is relatively portable between platforms. But falling back to where is not the nicest thing I agree. 

 Maybe just a fallback to a simple pure python solution instead? Would you be able to add something like that in your PR? 

It would be dead simple since there is already a `locate_binary()` function that searches the PATH here: https://github.com/scopatz/xonsh/blob/281b29f8d77d2f5e17ad500170f81862f7a9a8e7/xonsh/environ.py#L757

It is a little step towards pure python version...

**Comment by Will-W** [comment]
xonsh scripts are only going to be as portable as the availability of the programs that theyrun. If they want to run one built for Linux, they're going to need cygwin (or msys or whatever) anyway to provide the binaries. I don't see that `which` is any different to `ls` in this regard.

The only difference between `which` and `ls` is that we wrap `which` to add some alias looking up functionality. To me that doesn't imply that we should then be making `which` work cross-platform.

That's my way of thinking though, and if the consensus is for a portable version then I'll happily do it.

**Comment by melund** [comment]
@Will-W Implementing some of the core-utils in python is definitely something we want to do. See https://github.com/scopatz/xonsh/pull/742

I may speed up many things since don't have to since wrapping simple commands in subprocesses calls adds a lot of overhead. Especially on windows. 

I thought that having a python fall back if `which` could not be found would be a first step towards the goal. But it can also wait until we implement the entire thing in pure python. 

I am happy to merge your suggestion in if you think it is the best solution for now.

**Comment by Will-W** [comment]
Implementing which fully in Python would be more appropriate as part of that xoreutils task. In the meantime I think that this PR gives much better user feedback on Windows.

I've updated the CHANGELOG, so I think this is ready to merge.

**Comment by melund** [comment]
Thanks a lot @Will-W . Looks great

**Pull request merged**
