### PR TITLE
Don't crash if broken symlink on path.

### LINKED ISSUE #1061: #1041 broke xonsh if broken symlink on Path.
see comments I'm keeping in #1041.

### PR DESCRIPTION
**Pull request by Carreau**
closes #1061 

---- 

Might need tests.

### CODE REVIEW

**Comment by melund** [comment]
Yes. You are right. Test are definatly missing here. Btw. could this also happen with the Py34 block above that doesn't use `scandir()`? Do you (or anyone else on posix) mind testing this? Also do you mind adding an entry in the chagne log?

**Comment by Carreau** [comment]
Yes, I'll do that. 

I've chased bugs the rabbit hole on too many projects this morning. I'll try to get some work down and take care of that tomorrow.

**Comment by melund** [comment]
No problem. Thanks for effort :)

**Comment by Carreau** [comment]
Test added, hopefully will pass.

**Comment by melund** [comment]
Thanks a lot @Carreau

**Pull request merged**
