### PR TITLE
Nested Lists and Tuples

### LINKED ISSUE #61: Crash on parsing list nested in dict
When parsing a line containing a dict that has a list (or tuple) as a value, xonsh crashes.

```
bollmann@underberg ~/repositories/xonsh master >>> {'foo': ['a', 'b']}
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 12, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/bollmann/repositories/xonsh/scripts/xonsh", line 3, in <module>
    main()
  File "/home/bollmann/repositories/xonsh/xonsh/main.py", line 25, in main
    shell.cmdloop()
  File "/home/bollmann/repositories/xonsh/xonsh/shell.py", line 152, in cmdloop
    super(Shell, self).cmdloop(intro=intro)
  File "/usr/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.4/cmd.py", line 211, in onecmd
    return self.default(line)
  File "/home/bollmann/repositories/xonsh/xonsh/shell.py", line 105, in default
    code = self.push(line)
  File "/home/bollmann/repositories/xonsh/xonsh/shell.py", line 126, in push
    locs=self.ctx)
  File "/home/bollmann/repositories/xonsh/xonsh/execer.py", line 87, in compile
    code = compile(tree, self.filename, mode)
ValueError: Dict doesn't have the same number of keys as values
bollmann@underberg ~/repositories/xonsh (master) $ 
```

Other nested structures seem to work fine. Putting the list in a variable first and then constructing the dict also works fine.

```
bollmann@underberg ~/repositories/xonsh master >>> x = ['a', 'b']
bollmann@underberg ~/repositories/xonsh master >>> {'foo': x}
{'foo': ['a', 'b']}
bollmann@underberg ~/repositories/xonsh master >>> {'a': {'b': 'c', 'd': 'e'}}
{'a': {'b': 'c', 'd': 'e'}}
bollmann@underberg ~/repositories/xonsh master >>> [{'a': 'b', 'c': 'd'}]
[{'a': 'b', 'c': 'd'}]
bollmann@underberg ~/repositories/xonsh master >>> [{'a': 'b'}, {'c': 'd'}]
[{'a': 'b'}, {'c': 'd'}]
bollmann@underberg ~/repositories/xonsh master >>> {'a': {'b': 'c', 'd': 'e'}}
{'a': {'b': 'c', 'd': 'e'}}
```

### PR DESCRIPTION
**Pull request by scopatz**
This should fix #61

### CODE REVIEW

**Comment by wrywerytwreywery** [comment]
This fixes some things, but doesn't quite get the list-of-lists of list-of-tuples right; still acting weird on the first element, but a different kind of weird from before.

```
$ [[1],[2],[3],[4]]
[[1, [2], [3], [4]]]
```
```
$ [(1,), (2,), (3,)]
[(1, (2,), (3,))]
```

**Comment by mbollmann** [comment]
Can confirm it fixes #61 for me but has the same behaviour described by @wrywerytwreywery.

**Comment by wrywerytwreywery** [comment]
I believe I have a fix for this now.  I'll push a PR and update here shortly.

**Comment by scopatz** [comment]
I am going to keep working on this, since I think it is a little farther along than #122

**Comment by wrywerytwreywery** [comment]
Sounds good.  I will just close #122.

**Comment by scopatz** [comment]
Ok! I believe I have fixed this @wrywerytwreywery and @mbollmann.  Would you mind trying it out?

**Comment by scopatz** [comment]
Note that I rebased...

**Comment by wrywerytwreywery** [comment]
Looks good to me after some quick tests.

**Comment by mbollmann** [comment]
Yep, I couldn't produce anything invalid either.

**Comment by scopatz** [comment]
Thanks @mbollmann  and @wrywerytwreywery!

**Pull request merged**
