### PR TITLE
Jupyter Fixes

### PR DESCRIPTION
**Pull request by scopatz**
This implements a few small fixes to the Jupyter kernel that makes it usable.

### CODE REVIEW

**Comment by melund** [comment]
Wahoo... The kernel works for me now. It has been a while since I tried it. This is really awesome.

**Comment by scopatz** [comment]
Yay!  Do you want to merge this @melund?

**Comment by blink1073** [comment]
I'd recommend setting `os.environ['PAGER'] = 'cat'`, so you can get inline man pages.

**Comment by scopatz** [comment]
@blink1073 is that genreally applicable (i.e. windows). In any event, I think that could easily be another PR if this goes in before then.

**Comment by blink1073** [comment]
there is no "pager" on windows, but you could add an `if os.name != 'nt'` guard.

**Comment by scopatz** [comment]
I think that this requires a bit more thought because of things like cygwin.  It would be nice to just get this merged in and worry about the paging issues later, personally :)

**Comment by blink1073** [comment]
fair enough.

**Comment by blink1073** [comment]
for reference, that guard would work on Cygwin: http://stackoverflow.com/a/7637706

**Comment by scopatz** [comment]
I see, so I guess we'd want to use `xonsh.tools.ON_POSIX` rather than `xonsh.tools.ON_WINDOWS`: https://github.com/scopatz/xonsh/blob/master/xonsh/tools.py#L42

**Comment by melund** [comment]
Great. I think this is good, so I will go ahead and merge.

**Comment by blink1073** [comment]
:tada:  Were you planning a patch release for this?

**Comment by scopatz** [comment]
Yep.  I'll do it now.  It is now relatively easy to do a release because of our release script.

**Comment by scopatz** [comment]
Alright, The release is out.  Have at :)

**Pull request merged**
