### PR TITLE
Fix bugs in LimitedFileHistory plus tests

### PR DESCRIPTION
**Pull request by anula**
I've noticed a bug in LimitedFileHistory that I recently created, so I fixed it, added a few tests and fixed another bug ;)

### CODE REVIEW

**Comment by anula** [comment]
I also moved LimitedFileHistory from history.py to prompt_toolkit_history.py because it is needed only with prompt_toolkit version, and it needs prompt_toolkit to be used.
Problem with Travis build is connected with that fact - class for which I just added tests requires prompt_toolkit (because it inherits from prompt_toolkit's History) and Travis apparently doesn't include this library, because it returns following error:
```
ImportError: No module named 'prompt_toolkit' 
```
Any way to fix this?

**Comment by wrywerytwreywery** [comment]
> Any way to fix this?

I think you should be able to add `prompt_toolkit` to the modules that travis installs by adding `prompt_toolkit` to the "install" portion of [.travis.yml](https://github.com/scopatz/xonsh/blob/master/.travis.yml) (line 5).

**Comment by anula** [comment]
Ready to go.

**Comment by scopatz** [comment]
I am getting a test error locally (see below) for when prompt_toolkit is not installed.  Since this is optional, the test should skip.  With nose you do something like:

```
from nose.plugins.skip import SkipTest

def test_x():
     if not have_prompt_toolkit:
         raise SkipTest
```

Thanks for putting this in!


```console
scopatz@athenaie ~/xonsh/tests anula-history_tests $ nosetests 
..................................................................................Generating LALR tables
WARNING: 82 shift/reduce conflicts
WARNING: 10 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 20 resolved using rule (test_or_star_expr -> test)
WARNING: rejected rule (testlist -> test) in state 20
WARNING: reduce/reduce conflict in state 118 resolved using rule (string_literal -> STRING)
WARNING: rejected rule (subproc_arg_part -> STRING) in state 118
........................................................................................................................................................................................................................................................................................................................................................................................................................................................E...........................................
======================================================================
ERROR: Failure: ImportError (No module named 'prompt_toolkit')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/scopatz/miniconda3/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/scopatz/miniconda3/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/scopatz/xonsh/tests/test_prompt_toolkit_history.py", line 8, in <module>
    from xonsh.prompt_toolkit_history import LimitedFileHistory
  File "/home/scopatz/.local/lib/python3.4/site-packages/xonsh/prompt_toolkit_history.py", line 4, in <module>
    from prompt_toolkit.history import History
ImportError: No module named 'prompt_toolkit'

----------------------------------------------------------------------
Ran 566 tests in 1.836s

FAILED (errors=1)
scopatz@athenaie ~/xonsh/tests anula-history_tests $ 

```

**Comment by anula** [comment]
Ah, sorry for that, I assumed that dependencies for tests aren't so important.
Can you take another look?

**Comment by scopatz** [comment]
Thanks a million @anula!

**Pull request merged**
