### PR TITLE
py3.4 executables_in() performance

### PR DESCRIPTION
**Pull request by scopatz**
To restore what was removed in #975

### CODE REVIEW

**Comment by funkyfuture** [comment]
i rather thought to `from tools_34 import *` at the bottom of `tools`. (and to turn tools into a package.)

**Comment by scopatz** [comment]
> i rather thought to from tools_34 import * at the bottom of tools. (and to turn tools into a package.)

Sure, but this works for now.  Feel free to open up another PR!

**Comment by scopatz** [comment]
Ok, this now passes the tests :)

**Comment by melund** [comment]
LGTM

**Comment by scopatz** [comment]
Thanks @melund!

**Pull request merged**
