### PR TITLE
added login shell to bash

### PR DESCRIPTION
**Pull request by scopatz**
This might help with #313

### CODE REVIEW

**Comment by michaelaye** [comment]
Getting this now:
```python
klay6683@MacL2938 ~ $ aliases['cdsrc']
['cd', '$HOME/Dropbox/src']
klay6683@MacL2938 ~ $ cdsrc
cd: no such file or directory: $HOME/Dropbox/src
```

**Comment by scopatz** [comment]
I think that you could fix this by changing the alias in bash to `cd ~/Dropbox/src`

**Comment by michaelaye** [comment]
That's not a fix, that's a cheat. The user should not have to change her bash setup to make xonsh work.

**Comment by scopatz** [comment]
hey @melund - would you mind taking a look at this PR and possibly merging it?

**Comment by melund** [comment]
Hi @scopatz . I can't test it since I use Windows. However, reading up on bash, it seems reasonable. I can still click merge button if you want :)

The last issue raised by @michaelaye is another. I can't do that on windows either. 
`cd $USERPROFILE` works fine. But `cd $USERPROFILE/Documents` does not. In the shell, it is not a problem. If I press 'tab' the autocompleter expands it to the full path. Should we create an separate issue for it?

**Comment by scopatz** [comment]
> I can still click merge button if you want :)

Please do!

> Should we create an separate issue for it?

I think so.  Thanks!

**Comment by melund** [comment]
I have create a new issue for the problem reported by  @michaelaye 
https://github.com/scopatz/xonsh/issues/338

**Pull request merged**
