### PR TITLE
remove part of ptk shortcut fork that is no longer needed.

### PR DESCRIPTION
**Pull request by scopatz**
This reduces the amount of forked code that we have to something more manageable. However, it may require that users update to the latest PTK release (v0.57).  These methods were already flagged for removal so I don't think it is a big deal.

### CODE REVIEW

**Comment by gforsyth** [comment]
This seems pretty straightforward.  Do we want to add in a temporary warning if users fire up the `prompt_toolkit` shell with version `< 0.57`?

**Comment by scopatz** [comment]
Added the warning @gforsyth.

**Comment by gforsyth** [comment]
A little trouble here.  I happened to have `prompt_toolkit` 0.56 installed in one of my test environments and `xonsh` never makes it to the upgrade warning before this happens.

```Python
Traceback (most recent call last):
  File "/home/gil/anaconda/envs/xonshtesting/bin/xonsh", line 9, in <module>
    load_entry_point('xonsh==0.2.4', 'console_scripts', 'xonsh')()
  File "/home/gil/anaconda/envs/xonshtesting/lib/python3.5/site-packages/xonsh/main.py", line 190, in main
    shell.cmdloop()
  File "/home/gil/anaconda/envs/xonshtesting/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 103, in cmdloop
    line = self.singleline(auto_suggest=auto_suggest)
  File "/home/gil/anaconda/envs/xonshtesting/lib/python3.5/site-packages/xonsh/ptk/shell.py", line 72, in singleline
    display_completions_in_columns=multicolumn)
  File "/home/gil/anaconda/envs/xonshtesting/lib/python3.5/site-packages/xonsh/ptk/shortcuts.py", line 66, in prompt
    application=create_prompt_application(message, **kwargs),
TypeError: create_prompt_application() got an unexpected keyword argument 'reserve_space_for_menu'
```

**Comment by scopatz** [comment]
Ok, try it now @gforsyth.

**Comment by gforsyth** [comment]
Ok, `xonsh` starts up now even with an older version of `prompt_toolkit` and warns about potential issues.  Merging this in.

**Pull request merged**
