### PR TITLE
run xonfig wizard from main thread

### LINKED ISSUE #770: CTRL-C during config wizard results in loss of input to terminal
Running bash in a Terminator window, when I first started xonsh, I was asked if I wanted to run the config wizard.  I chose yes, but then eventually decided I didn't want to finish, so I hit CTRL-C.  This eventually got me back to bash, but when I pressed keys, the keys didn't show up in the terminal windows.  I had to close the window and open a new one.

### PR DESCRIPTION
**Pull request by scopatz**
In my testing this fixes #770.  @rsyring would you mind testing this out?

### CODE REVIEW

**Comment by melund** [comment]
This works for me ;)

**Comment by scopatz** [comment]
Feel free to merge then @melund :)

**Comment by melund** [comment]
I will. . @rsyring let us know if this somehow didn't fix it for you

**Comment by melund** [comment]
Hmm... That change log is getting long. Another merge conflict. @scopatz

**Comment by rsyring** [comment]
I won't be able to test until tonight or tomorrow.

Randy Syring (sent from my mobile)
Chief Executive Developer
Direct: 502-276-0459
Office: 812-285-8766

Level 12 - Principled People | Software that Works

**Comment by scopatz** [comment]
Updated @melund. And I agree the changelog is looking long.  I am hoping to do a release before PyCon.

@rsyring, thanks! That works for me.

**Comment by rsyring** [comment]
I can confirm this branch fixes the issue I had in #770.

**Comment by scopatz** [comment]
Thanks @rsyring!

**Pull request merged**
